; RDR2 Rampage - Add 1 of every provision
; FIXED VERSION - does NOT use clipboard paste.
; Requires AutoHotkey v2.
;
; The previous version failed because Rampage's in-game Custom input
; does not reliably accept Ctrl+V. This version sends real keyboard
; events for every character.
;
; HOW TO USE
; 1. Start RDR2 Story Mode and open Rampage.
; 2. Go to Character Stats -> Items -> Add to Inventory.
; 3. Open the "Custom" input so the blinking text cursor is visible.
; 4. Press F8.
;
; F9  = pause/resume
; F10 = stop
;
; IMPORTANT:
; This version assumes Rampage's Add to Inventory custom entry adds
; one item when the item identifier is submitted. It does NOT type a
; separate quantity "1" after each name, because your recording shows
; that doing so was being entered into the same Custom text field.
;
; Start with F7 TEST first. It enters PROVISION_ANIMAL_FAT only.
; If Rampage accepts that correctly, reopen Custom and press F8.

#Requires AutoHotkey v2.0
#SingleInstance Force
SetKeyDelay(18, 18)

global Running := false
global Paused := false
global StopRequested := false

; Adjust these if your menu is slower.
CharDelay := 4
AfterSubmitDelay := 450
ReopenDelay := 250

Items := [
    "PROVISION_ALLIGATOR_LEGENDARY_SKIN_PRISTINE",
    "PROVISION_ALLIGATOR_SKIN_PRISTINE",
    "PROVISION_ANIMAL_CARCASS_ALLIGATOR_PERFECT",
    "PROVISION_ANIMAL_CARCASS_ARMADILLO_PERFECT",
    "PROVISION_ANIMAL_CARCASS_BADGER_PERFECT",
    "PROVISION_ANIMAL_CARCASS_BAT_PERFECT",
    "PROVISION_ANIMAL_CARCASS_BEAVER_LEGENDARY_PERFECT",
    "PROVISION_ANIMAL_CARCASS_BEAVER_PERFECT",
    "PROVISION_ANIMAL_CARCASS_BIGHORN_RAM_LEGENDARY_PERFECT",
    "PROVISION_ANIMAL_CARCASS_BIGHORN_SHEEP_PERFECT",
    "PROVISION_ANIMAL_CARCASS_BLUEJAY_PERFECT",
    "PROVISION_ANIMAL_CARCASS_BOBCAT_PERFECT",
    "PROVISION_ANIMAL_CARCASS_BUCK_LEGENDARY_PERFECT",
    "PROVISION_ANIMAL_CARCASS_BUCK_PERFECT",
    "PROVISION_ANIMAL_CARCASS_BULLFROG_PERFECT",
    "PROVISION_ANIMAL_CARCASS_CALICONDOR_PERFECT",
    "PROVISION_ANIMAL_CARCASS_CARDINAL_PERFECT",
    "PROVISION_ANIMAL_CARCASS_CEDARWAXWING_PERFECT",
    "PROVISION_ANIMAL_CARCASS_CHICKEN_PERFECT",
    "PROVISION_ANIMAL_CARCASS_CHIPMUNK_PERFECT",
    "PROVISION_ANIMAL_CARCASS_CORMORANT_PERFECT",
    "PROVISION_ANIMAL_CARCASS_COUGAR_LEGENDARY_PERFECT",
    "PROVISION_ANIMAL_CARCASS_COUGAR_PERFECT",
    "PROVISION_ANIMAL_CARCASS_COYOTE_LEGENDARY_PERFECT",
    "PROVISION_ANIMAL_CARCASS_COYOTE_PERFECT",
    "PROVISION_ANIMAL_CARCASS_CRAB_PERFECT",
    "PROVISION_ANIMAL_CARCASS_CRANE_PERFECT",
    "PROVISION_ANIMAL_CARCASS_CRAWFISH_PERFECT",
    "PROVISION_ANIMAL_CARCASS_CRLNAPARKET_PERFECT",
    "PROVISION_ANIMAL_CARCASS_CROW_PERFECT",
    "PROVISION_ANIMAL_CARCASS_DEER_PERFECT",
    "PROVISION_ANIMAL_CARCASS_DUCK_PERFECT",
    "PROVISION_ANIMAL_CARCASS_EAGLE_PERFECT",
    "PROVISION_ANIMAL_CARCASS_EGRET_PERFECT",
    "PROVISION_ANIMAL_CARCASS_FOX_LEGENDARY_PERFECT",
    "PROVISION_ANIMAL_CARCASS_FOX_PERFECT",
    "PROVISION_ANIMAL_CARCASS_GILA_PERFECT",
    "PROVISION_ANIMAL_CARCASS_GOAT_PERFECT",
    "PROVISION_ANIMAL_CARCASS_GOOSE_PERFECT",
    "PROVISION_ANIMAL_CARCASS_HAWK_PERFECT",
    "PROVISION_ANIMAL_CARCASS_HERON_PERFECT",
    "PROVISION_ANIMAL_CARCASS_IGUANA_PERFECT",
    "PROVISION_ANIMAL_CARCASS_LOON_PERFECT",
    "PROVISION_ANIMAL_CARCASS_MUSKRAT_PERFECT",
    "PROVISION_ANIMAL_CARCASS_OPOSSUM_PERFECT",
    "PROVISION_ANIMAL_CARCASS_ORIOLE_PERFECT",
    "PROVISION_ANIMAL_CARCASS_OWL_PERFECT",
    "PROVISION_ANIMAL_CARCASS_PANTHER_LEGENDARY_PERFECT",
    "PROVISION_ANIMAL_CARCASS_PANTHER_PERFECT",
    "PROVISION_ANIMAL_CARCASS_PARROT_PERFECT",
    "PROVISION_ANIMAL_CARCASS_PELICAN_PERFECT",
    "PROVISION_ANIMAL_CARCASS_PERFECT",
    "PROVISION_ANIMAL_CARCASS_PHEASANT_PERFECT",
    "PROVISION_ANIMAL_CARCASS_PIGEON_PERFECT",
    "PROVISION_ANIMAL_CARCASS_PIG_PERFECT",
    "PROVISION_ANIMAL_CARCASS_PRARECHICK_PERFECT",
    "PROVISION_ANIMAL_CARCASS_PRONGHORN_LEGENDARY_PERFECT",
    "PROVISION_ANIMAL_CARCASS_PRONGHORN_PERFECT",
    "PROVISION_ANIMAL_CARCASS_QUAIL_PERFECT",
    "PROVISION_ANIMAL_CARCASS_RABBIT_PERFECT",
    "PROVISION_ANIMAL_CARCASS_RACOON_PERFECT",
    "PROVISION_ANIMAL_CARCASS_RAM_PERFECT",
    "PROVISION_ANIMAL_CARCASS_RAT_PERFECT",
    "PROVISION_ANIMAL_CARCASS_RAVEN_PERFECT",
    "PROVISION_ANIMAL_CARCASS_REDFTBOOBY_PERFECT",
    "PROVISION_ANIMAL_CARCASS_ROBIN_PERFECT",
    "PROVISION_ANIMAL_CARCASS_ROOSTER_PERFECT",
    "PROVISION_ANIMAL_CARCASS_ROSESPOONBIL_PERFECT",
    "PROVISION_ANIMAL_CARCASS_SEAGULL_PERFECT",
    "PROVISION_ANIMAL_CARCASS_SHEEP_PERFECT",
    "PROVISION_ANIMAL_CARCASS_SKUNK_PERFECT",
    "PROVISION_ANIMAL_CARCASS_SNAKE_BLRAT_PERFECT",
    "PROVISION_ANIMAL_CARCASS_SNAKE_BOA_PERFECT",
    "PROVISION_ANIMAL_CARCASS_SNAKE_COPPER_PERFECT",
    "PROVISION_ANIMAL_CARCASS_SNAKE_FERDLNCE_PERFECT",
    "PROVISION_ANIMAL_CARCASS_SNAKE_PERFECT",
    "PROVISION_ANIMAL_CARCASS_SNAKE_WATER_PERFECT",
    "PROVISION_ANIMAL_CARCASS_SONGBIRD_PERFECT",
    "PROVISION_ANIMAL_CARCASS_SPARROW_PERFECT",
    "PROVISION_ANIMAL_CARCASS_SQUIRREL_PERFECT",
    "PROVISION_ANIMAL_CARCASS_TOAD_PERFECT",
    "PROVISION_ANIMAL_CARCASS_TURKEY_PERFECT",
    "PROVISION_ANIMAL_CARCASS_TURTLE_SNAP_PERFECT",
    "PROVISION_ANIMAL_CARCASS_VULTURE_PERFECT",
    "PROVISION_ANIMAL_CARCASS_WOLF_LEGENDARY_PERFECT",
    "PROVISION_ANIMAL_CARCASS_WOLF_PERFECT",
    "PROVISION_ANIMAL_CARCASS_WOODPECKER_PERFECT",
    "PROVISION_ARMADILLO_SKIN_PRISTINE",
    "PROVISION_BADGER_PELT_PRISTINE",
    "PROVISION_BEAR_FUR_PRISTINE",
    "PROVISION_BEAR_LEGENDARY_FUR_PRISTINE",
    "PROVISION_BEAVER_FUR_PRISTINE",
    "PROVISION_BEAVER_LEGENDARY_FUR_PRISTINE",
    "PROVISION_BLACK_BEAR_FUR_PRISTINE",
    "PROVISION_BOAR_LEGENDARY_SKIN_PRISTINE",
    "PROVISION_BOAR_SKIN_PRISTINE",
    "PROVISION_BUCK_FUR_PRISTINE",
    "PROVISION_BUCK_LEGENDARY_FUR_PRISTINE",
    "PROVISION_BUFFALO_FUR_PRISTINE",
    "PROVISION_BULL_HIDE_PRISTINE",
    "PROVISION_COUGAR_FUR_PRISTINE",
    "PROVISION_COUGAR_LEGENDARY_FUR_PRISTINE",
    "PROVISION_COW_HIDE_PRISTINE",
    "PROVISION_COYOTE_FUR_PRISTINE",
    "PROVISION_COYOTE_LEGENDARY_FUR_PRISTINE",
    "PROVISION_DEER_HIDE_PRISTINE",
    "PROVISION_ELK_FUR_PRISTINE",
    "PROVISION_ELK_LEGENDARY_FUR_PRISTINE",
    "PROVISION_FOX_FUR_PRISTINE",
    "PROVISION_FOX_LEGENDARY_FUR_PRISTINE",
    "PROVISION_FROG_SKIN_PRISTINE",
    "PROVISION_GILA_SKIN_PRISTINE",
    "PROVISION_GOAT_HAIR_PRISTINE",
    "PROVISION_IGUANA_SKIN_PRISTINE",
    "PROVISION_JAVELINA_SKIN_PRISTINE",
    "PROVISION_MOOSE_FUR_PRISTINE",
    "PROVISION_MOOSE_LEGENDARY_FUR_PRISTINE",
    "PROVISION_MUSKRAT_FUR_PRISTINE",
    "PROVISION_OPOSSUM_FUR_PRISTINE",
    "PROVISION_OXEN_HIDE_PRISTINE",
    "PROVISION_PANTHER_FUR_PRISTINE",
    "PROVISION_PANTHER_LEGENDARY_FUR_PRISTINE",
    "PROVISION_PIG_SKIN_PRISTINE",
    "PROVISION_PRONGHORN_FUR_PRISTINE",
    "PROVISION_PRONGHORN_LEGENDARY_FUR_PRISTINE",
    "PROVISION_RABBIT_PELT_PRISTINE",
    "PROVISION_RACCOON_FUR_PRISTINE",
    "PROVISION_RAM_HIDE_PRISTINE",
    "PROVISION_RAM_LEGENDARY_HIDE_PRISTINE",
    "PROVISION_RAT_FUR_PRISTINE",
    "PROVISION_SHEEP_WOOL_PRISTINE",
    "PROVISION_SKUNK_FUR_PRISTINE",
    "PROVISION_SNAKE_SKIN_PRISTINE",
    "PROVISION_SQUIRREL_PELT_PRISTINE",
    "PROVISION_TAKANTA_BUFFALO_LEGENDARY_FUR_PRISTINE",
    "PROVISION_WHITE_BUFFALO_LEGENDARY_FUR_PRISTINE",
    "PROVISION_WOLF_FUR_PRISTINE",
    "PROVISION_WOLF_LEGENDARY_FUR_PRISTINE"
]

TypeRampageText(text) {
    global CharDelay
    ; SendText generates actual text keystrokes rather than clipboard paste.
    ; Sending one character at a time is slower but much more reliable in
    ; Rockstar/Rampage native text-entry boxes.
    for ch in StrSplit(text) {
        SendText(ch)
        Sleep(CharDelay)
    }
}

PressGameEnter() {
    ; Lower-level Windows keyboard event for the main Enter key.
    ; VK_RETURN = 0x0D, scan code = 0x1C.
    ; First call = key down, second call with KEYEVENTF_KEYUP = key up.
    DllCall("keybd_event", "UChar", 0x0D, "UChar", 0x1C, "UInt", 0, "UPtr", 0)
    Sleep(100)
    DllCall("keybd_event", "UChar", 0x0D, "UChar", 0x1C, "UInt", 0x0002, "UPtr", 0)
    Sleep(150)
}

; ENTER TEST
; Open Rampage's Custom text box and press F6.
; It should act exactly like pressing the physical Enter key once.
F6::{
    ToolTip("Sending scan-code Enter...")
    PressGameEnter()
    Sleep(1000)
    ToolTip()
}

; TEST ONE ITEM FIRST
F7::{
    ToolTip("Typing one test item...")
    TypeRampageText("PROVISION_ANIMAL_FAT")
    Sleep(150)
    PressGameEnter()
    ToolTip("Test submitted: PROVISION_ANIMAL_FAT")
    Sleep(1800)
    ToolTip()
}

F8::{
    global Running, Paused, StopRequested, Items
    global AfterSubmitDelay, ReopenDelay

    if Running
        return

    Running := true
    Paused := false
    StopRequested := false

    for index, item in Items {
        if StopRequested
            break

        while Paused && !StopRequested
            Sleep(100)

        if StopRequested
            break

        ToolTip("Rampage provisions: " index "/" Items.Length "`n" item "`nF9 pause | F10 stop")

        ; The Custom dialog must already be open for the first item.
        TypeRampageText(item)
        Sleep(100)
        ; Submit the provision identifier.
        PressGameEnter()
        Sleep(5000)

        ; Quantity screen: keep the existing "1" and type a 0 after it -> "10".
        SendText("0")
        Sleep(300)
        PressGameEnter()
        Sleep(2000)

        ; Re-select Rampage's "Add to Inventory" option.
        PressGameEnter()
        Sleep(2000)

        ; Give Rampage time before typing the next item.
        Sleep(AfterSubmitDelay)

        if index < Items.Length {
            ; Wait before typing the next provision.
            Sleep(ReopenDelay)
        }
    }

    ToolTip(StopRequested ? "Stopped." : "Finished attempting all " Items.Length " entries.")
    Sleep(2500)
    ToolTip()
    Running := false
}

F9::{
    global Running, Paused
    if !Running
        return
    Paused := !Paused
    ToolTip(Paused ? "Paused - F9 to resume" : "Resumed")
    Sleep(700)
    ToolTip()
}

F10::{
    global StopRequested
    StopRequested := true
}
